### PR TITLE
Simplify idempotency check

### PR DESCRIPTION
**Pull request by maltewhiite**
If the receipt is only for idempotency, then we can simply use "creates" instead. 

I am not sure if I am fulfilling all requirements here. 

Closes https://github.com/puppetlabs/puppetlabs-docker/issues/842

### CODE REVIEW

**Comment by maltewhiite** [comment]
Last commit was to fix failing check: https://github.com/puppetlabs/puppetlabs-docker/runs/6862356563?check_suite_focus=true

**Comment by chelnak** [comment]
Hey @maltewhiite - I'm not sure on the state of this PR.

The associated issue states that `create` doesn't fix the problem. I'm also not sure that suggested implementation is the correct route for a fix.

Thanks!

**Comment by chelnak** [comment]
Hey @maltewhiite, I'm going to close this PR for now. As I mentioned in the previous comment, I'm not sure if the suggested implementation is the right way to attack this issue.

If you have any other ideas, please do open another PR.

In the meantime, I'd like thank you for your contribution!

**Comment by maltewhiite** [comment]
@chelnak all good. My team made a local fix to the problem.

**Comment by chelnak** [comment]
@maltewhiite You too! Thanks again for the contribution.

**Pull request closed without merging**
