### PR TITLE
Update Docker Compose to handle symbols

### PR DESCRIPTION
**Pull request by sili72**

### CODE REVIEW

**Comment by smortex** [comment]
@sili72 can you please elaborate on what this is intended to fix?  Thanks!

**Comment by tuxmea** [comment]
@bastelfreak 

Can someone please retrigger the Windows 2022 tests.

Failing reason:
```
RuntimeError:
        {"_error"=>{"details"=>{}, "kind"=>"puppetlabs.tasks/connect-error", "msg"=>"Timeout after 10 seconds connecting to http://35.230.80.103:5985/wsman", "issue_code"=>"CONNECT_ERROR"}}
```

**Comment by tuxmea** [comment]
> @sili72 can you please elaborate on what this is intended to fix? Thanks!

@smortex When running docker compose it can happen that the output contain symbols.
As of Puppet 7 and the underlying Ruby Version have a breaking change in yaml.safe_load, we must explicitly allow symbols.

**Comment by chelnak** [comment]
@tuxmea Just to clarify, by symbols do you mean extended ASCII characters?

**Comment by chelnak** [comment]
> @bastelfreak 
> 
> 
> 
> Can someone please retrigger the Windows 2022 tests.
> 
> 
> 
> Failing reason:
> 
> ```
> 
> RuntimeError:
> 
>         {"_error"=>{"details"=>{}, "kind"=>"puppetlabs.tasks/connect-error", "msg"=>"Timeout after 10 seconds connecting to http://35.230.80.103:5985/wsman", "issue_code"=>"CONNECT_ERROR"}}
> 
> ```
> 
> 

I'll do this now.

If you ever need us, you should be able to ping out group @puppetlabs/modules 🙂

**Comment by tuxmea** [comment]
> @tuxmea Just to clarify, by symbols do you mean extended ASCII characters?

No, its about ruyb symbols. Maybe the following link helps: https://www.ctrl.blog/entry/ruby-psych4.html

**Comment by chelnak** [comment]
> > @tuxmea Just to clarify, by symbols do you mean extended ASCII characters?
> 
> @chelnak No, its about ruby symbols. Maybe the following link helps: https://www.ctrl.blog/entry/ruby-psych4.html

Fantastic, thanks so much for that link. Makes sense now.  I can see that there has been a similar issue [with vmpooler](https://github.com/puppetlabs/vmpooler/issues/240).

I'll be working on docker today so will get this merged once CI completes 😄

**Review by LukasAud — APPROVED** [review]

**Pull request merged**
