### PR TITLE
I made a commit that will simplify the docker_params_changed function

### PR DESCRIPTION
**Pull request by wilful**
The old script is very heavily overloaded, I made it more DRY compatible
But I don't know how to write and check with SPEC file

### CODE REVIEW

**Comment by wilful** [comment]
omg, i don't know how fix it =(

**Comment by GSPatton** [comment]
Hi @wilful. Could you update your PR description and title to be more descriptive about what this PR is trying to achieve? Thank you!

**Comment by GSPatton** [comment]
also, can you rebase your branch with the main branch?

**Comment by wilful** [comment]
sry, no time yet to figure it out, maybe later I will return to this issue ((

**Comment by LukasAud** [comment]
Looks like our tests didnt properly kick in last time there was a push. Closing and re-opening PR to restart them.

**Comment by GSPatton** [comment]
closing stale PR due to inactivity. Feel free to reopen if you feel like continuing work at some later time.

**Pull request closed without merging**
