### PR TITLE
fixing issue #689 by setting HOME in docker command

### PR DESCRIPTION
**Pull request by sdinten**

### CODE REVIEW

**Comment by deubert-it** [comment]
Thanks a lot for the fix!

**Review by adrianiurca — APPROVED** [review]

**Comment by ahoiroman** [comment]
Thank you for your fix. Any chance to get a new release for this? I would love to deploy this using `puppet module install`.

**Comment by sdinten** [comment]
> 
> 
> Thank you for your fix. Any chance to get a new release for this? I would love to deploy this using� `puppet module install`.

@adrianiurca is there anything I can do to get this released?

**Comment by adrianiurca** [comment]
> > Thank you for your fix. Any chance to get a new release for this? I would love to deploy this using� `puppet module install`.
> 
> @adrianiurca is there anything I can do to get this released?

@sdinten it will be released today, or at the latest tomorrow

**Pull request merged**
