### PR TITLE
Refactor RSpec tests

### PR DESCRIPTION
**Pull request by crazymind1337**
I have rewritten all rspec tests using shared_examples. I have mostly taken the test cases from the old rspecs.

- now every supported operating system from metadata.json is been tested
- introduce shared_examples

I have also made a tiny bugfix which occured while writing the tests and other changes to manifests are only sorting of variables.

### CODE REVIEW

**Comment by crazymind1337** [comment]
A complete run via `bundle exec rake parallel_spec`:

```
Finished in 6 minutes 28 seconds (files took 1 minute 49.05 seconds to load)
1954 examples, 0 failures


Code coverage
  must cover at least 0% of resources
Total resources:   135
Touched resources: 132
Resource coverage: 97.78%

Untouched resources:
  File[/etc/default/my-docker]
  File[/usr/local/bin/docker-run-command-stop.sh]
  File[C:/ProgramData/docker/config/daemon.json]

3758 examples, 0 failures
```

There still 3 resources missing. I will add them later after this PR has been merged.

**Comment by crazymind1337** [comment]
I still have to fix `rubocop`-test.

**Comment by crazymind1337** [comment]
I did some final edits after reviewing my own changes.

**Comment by crazymind1337** [comment]
I am still missing some `content => ...` tests since I had no good idea how to test epp or erb for whole content.

**Comment by sanfrancrisko** [comment]
@crazymind1337 Are you still intending to address the Rubocop violations and remove them from the `TODO` list? If so, we might want to make this PR a draft until it's ready for review?

**Comment by crazymind1337** [comment]
> @crazymind1337 Are you still intending to address the Rubocop violations and remove them from the `TODO` list? If so, we might want to make this PR a draft until it's ready for review?

Oh, I really forget about that. I have moved all but one of the rubocop_todos to the .rubocop.yaml. I was able to remove one of the completly.

**Comment by crazymind1337** [comment]
I am wondering why the `ubuntu1604 / LitmusAcceptance`-test is failing now. Any ideas?

**Comment by sanfrancrisko** [comment]
Thanks for this PR @crazymind1337 - quite an effort, but very much appreciated. I've been reviewing a bit today, but given the size, it'll likely take another bit of time, but we'll try to get it over the line as soon as we can.

**Comment by crazymind1337** [comment]
Any progress?

**Comment by sanfrancrisko** [comment]
@crazymind1337 Apologies for the delay - I have been reviewing and testing your changes and they look good. A few last things I want to do but some other high priority stuff came in and blew everything out of the water - I'll try to get back to this early next week and merged by the end of next week.

**Comment by david22swan** [comment]
@crazymind1337 
Making a quick change to point this PR towards the newly defined default main branch as part of our work to remove inappropriate terminology. Apologies if this is inconvenient in any way.

**Comment by crazymind1337** [comment]
> @crazymind1337
> Making a quick change to point this PR towards the newly defined default main branch as part of our work to remove inappropriate terminology. Apologies if this is inconvenient in any way.

I have rebase onto the new default branch.

**Comment by sanfrancrisko** [comment]
Thanks for your patience @crazymind1337 - I'm rotating on triage from later today, so I'll make your PR the first priority.

**Comment by crazymind1337** [comment]
Stay calm. No stress please! :D

**Comment by crazymind1337** [comment]
Wohoo!!

**Pull request merged**
