### PR TITLE
Rename service_update to swarm_update for consistency

### PR DESCRIPTION
**Pull request by khaefeli**
Use a consistent name for the puppet tasks and the files.

### CODE REVIEW

**Comment by sheenaajay** [comment]
Thanks @khaefeli for submitting the PR.
Could you please add the deprecation warning to the old task so the current users will be automatically redirected to the renamed task. Thank you.

**Comment by khaefeli** [comment]
Hey @DavidS, I'll probably won't have the time to fix it within the next 1-2month.

**Comment by DavidS** [comment]
Same here - we're only running skeleton crew over the holidays! 

Guten Rutsch!

**Comment by sanfrancrisko** [comment]
Thank you @khaefeli for your PR. There does not seem to have been any activity on this PR for 90 days, therefore it will be closed. Please feel free to reopen again in the future and we will be happy to assist in any way we can.

Thanks!
Puppet IAC Team

**Pull request closed without merging**
