### PR TITLE
Fix regex for installing docker-ce version 17.06 onwards

### LINKED ISSUE #564: Unable to install docker-ce 17.06 onwards
## Describe the Bug

#490 has broken ability to install Docker 17.x > 17.05

For example, the regex on https://github.com/puppetlabs/puppetlabs-docker/blob/af994cc3855f3530a2afb396c2e8db7ad97986cb/manifests/init.pp#L597 incorrectly matches `17.12.0~ce-0~debian`, causing Puppet to try and install `docker-engine=17.12.0~ce-0~debian` which does not exist.

## Expected Behavior

Regex should match version 17 only up to 17.05 to allow `docker-ce` to be installed for Docker >=17.06

## Steps to Reproduce

```puppet
	class {'docker':
		version				=> '17.12.0~ce-0~debian'
	}
```

## Environment

Debian Stretch

### PR DESCRIPTION
**Pull request by matthanley**
Closes #564

### CODE REVIEW

**Comment by sheenaajay** [comment]
Thank you @matthanley for submitting the PR. Could you please fix the Travis failures and also add a test to verify the change. Thank you.

**Comment by david22swan** [comment]
@matthanley Just checking the status of this pr?

**Comment by matthanley** [comment]
@david22swan as far as I can see the Travis failures weren't related to my (single line regex fix) change, and I've not had time to add test coverage

**Comment by david22swan** [comment]
@matthanley Could you try rebasing your work onto the master to see if that fixes the travis failures?

**Comment by michaeltlombardi** [comment]
It looks like this pull request hasn't seen any activity in a while, @matthanley. Is this something that you're still able to work on? We're happy to keep this pull request open if there's forward movement, and we'll leave it open for another two weeks from now. If there isn't any activity by then we may have to close this pull request due to lack of activity.

  Closing the pull request wouldn't mean we don't consider this change valuable. However we try to keep all open pull requests moving towards completion, and closing stale pull requests help us focus on more active pull requests.

  If you have any questions or concerns, please don't hesitate to ping us in the Slack channel on slack.puppet.com.

**Comment by david22swan** [comment]
@matthanley 
Making a quick change to point this PR towards the newly defined default main branch as part of our work to remove inappropriate terminology. Apologies if this is inconvenient in any way.

**Comment by sanfrancrisko** [comment]
Hi @matthanley  - I'm just closing this PR as part of the IAC Team's audit of stale PRs. I think this would be a useful fix, but, implementation wise, I'd prefer to come up with something that is more long term. I was trying to do this with something I outlined in [IAC-1039](https://tickets.puppetlabs.com/browse/IAC-1039), however it's going to be a bit more involved than originally anticipated.

Thanks for the submission and ping us any time if you want to pick it up again.

**Pull request closed without merging**
