### PR TITLE
major adjustments for current code style

### PR DESCRIPTION
**Pull request by crazymind1337**
I have made a general linting for all manifests.

- lint and indent for all class and defined types parameters
- fixed several data type usages
- lint and indent of all manifests
- dropped usage of legacy facts
- switched to puppet strings layout
  - added missing parameter to list (without description)
  - removed dropped parameter from list
  - generated new REFERENCE.md

### CODE REVIEW

**Comment by crazymind1337** [comment]
I want to add support for Ubuntu focal fossa, but I did not like the code style, so I adjusted it.

**Comment by crazymind1337** [comment]
Fixing those rspec error for migrated $facts is quite a mess.

**Comment by david22swan** [comment]
@crazymind1337 Thanks for the work :)

**Comment by genebean** [comment]
Nice work @crazymind1337! I saw you mention this in slack - always nice to see people take the time to make things match current standards :)

**Comment by crazymind1337** [comment]
> Nice work @crazymind1337! I saw you mention this in slack - always nice to see people take the time to make things match current standards :)

Thats the way open source is working ;-)

**Pull request merged**
