### PR TITLE
Only install docker-ce-cli with docker-ce

### PR DESCRIPTION
**Pull request by vchepkov**
rebase to main of #798

### CODE REVIEW

**Comment by vchepkov** [comment]
I have no idea why identical change on master succeeded and on top on main failed.
I see @kenyon is back, so I am happy to bug out

**Comment by chelnak** [comment]
It could be transient windows issues. We can re kick the tests.

**Comment by kenyon** [comment]
The Windows test failures are unrelated, apparently due to network problems.

**Comment by chelnak** [comment]
@kenyon Yeah thats right. Windows can be a bit flakey sometimes. Looks like we are all green now though.

**Pull request merged**
